services:
  redis:
    image: redis:alpine
    container_name: ${DOCKER_REDIS_SERVICE_NAME}
    networks:
      - backend
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
 
  ms-incidentes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-incidentes
    networks:
      - backend
    ports:
      - '${DOCKER_BACKEND_PORT}:8080'
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
 
networks:
  backend:
    external: true
    name: prueba