services:
  redis:
    image: redis:alpine
    container_name: ${DOCKER_REDIS_SERVICE_NAME}
    networks:
      - backend
    ports:
      - '${DOCKER_REDIS_PORT}:6379'

  db-primary:
    image: mysql:8.0
    container_name: db-primary
    networks:
      - backend
    ports:
      - '0.0.0.0:3306:${DB_PORT_PRIMARY}'
    env_file:
      - .env
    environment:
        MYSQL_ROOT_PASSWORD: password  
        MYSQL_DATABASE: incidentes

  db-replica:
    image: mysql:8.0
    container_name: db-replica
    networks:
      - backend
    ports:
      - '0.0.0.0:3307:${DB_PORT_REPLICA}'
    env_file:
      - .env
    environment:
        MYSQL_ROOT_PASSWORD: password  
        MYSQL_DATABASE: incidentes
    
  ms-incidentes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-incidentes
    networks:
      - backend
    ports:
      - '${DOCKER_BACKEND_PORT}:8080'
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env

    depends_on:
      - db-primary
      - db-replica
 
networks:
  backend:
    external: true
    name: prueba