name: Build
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9, 3.10]  # Define las versiones de Python que deseas probar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Necesario para SonarCloud
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml -o coverage.xml  # Genera el reporte de cobertura en formato XML
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ms-incidentes
            -Dsonar.organization=ABCall-G13
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml  # Especifica la ruta del reporte de cobertura
